<?php
/**
 * @var $block \Buzzi\PublishProductView\Block\EventTrigger
 */
?>

<div class="buzzi-product-view-container" data-role="buzzi-product-view" data-bind="scope: 'buzzi-product-view-container'">
</div>

<script type="text/x-magento-init">
    {
        "[data-role=buzzi-product-view]": {
            "Buzzi_PublishProductView/js/event-trigger": {
                "event_type": "<?= $block->escapeJsQuote($block->getEventType(), "\"") ?>",
                "product_sku": "<?= $block->escapeJsQuote($block->getProductSku(), "\"") ?>"
            }
        }
    }
</script>
